version: "3.8"

services:
  mysqldb:
    image: mysql:8.3.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=devops
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  app:
    depends_on:
      - mysqldb
    build: ./
    restart: always
    ports:
      - 8082:8082
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - .m2:/root/.m2
      - ./src/main/resources:/app/src/main/resources
    stdin_open: true
    tty: true

volumes:
  db:
